language: node_js
 
before_install:
 - sudo apt-get install libgmp3-dev
 - "mysql -e 'create database myapp_test;'"

mysql:
  adapter: mysql2
  encoding: utf8

node_js:
 - 0.6

env:
 - DB=mysql NODE_ENV=test_mysql

notifications:
  irc: "irc.mozilla.org#identity"
